site_name: Parking 4.0
nav:
    - Introducción: index.md
    - Git uso y comandos basicos: Git.md
    - Docker uso y comandos básicos: Docker.md
    - Documentacion, Mkdocs: Mkdocss.md
    - Documentacion, Markdown: Markdown.md
    - Python flask uso basico: Pythonflask.md
theme: 
  name: material